# Generated by Django 4.2.1 on 2023-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='video',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
